"""
=========================
Test Framework Exceptions
=========================

This module contains the DTestException class, which is an extension
raised by the framework when an error is encountered while executing
functions or methods of the framework itself.
"""

class DTestException(Exception):
    """
    DTestException
    ==============

    The DTestException is an exception class used for all exceptions
    generated by the test framework.
    """

    pass
